apiVersion: v1
kind: Service
metadata:
  labels:
    app: annotation
  name: annotation
  namespace: {{ .Release.Namespace }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: annotation
  sessionAffinity: None
  type: "{{ .Values.serviceType }}"
