apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "svc.name" . }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "svc.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ template "svc.name" . }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}"
        app: "{{ template "svc.name" . }}"
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
      - image: "{{ .Values.image.registry }}/assets:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        name: users
        resources:
{{ toYaml .Values.resources | indent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: users
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users
              key: POSTGRES_PASSWORD
        - name: POSTGRES_PORT
          value: "{{ default .Values.global.db.port .Values.db.port  }}"
        - name: POSTGRES_DB
          value: "{{ .Values.db.name }}"
        - name: POSTGRES_HOST
          value: "{{ default .Values.global.db.host .Values.db.host }}"
        - name: MINIO_URI
          value: "{{ default .Values.global.s3.endpoint .Values.s3.endpoint }}"
          {{- if .Values.secret.s3user }}
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: users
              key: S3_LOGIN
          {{- end }}
          {{- if .Values.secret.s3password }}
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: users
              key: S3_PASS
          {{- end }}
        - name: KEYCLOAK_ENDPOINT
          value: "{{ .Values.keycloak.internalUrl }}"
        - name: KEYCLOAK_DIRECT_ENDPOINT
          value: "{{ .Values.keycloak.externalUrl }}"
        - name: KEYCLOAK_USERS_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: users-keycloak
              key: KEYCLOAK_USERS_PUBLIC_KEY
        - name: BADGERDOC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: users-keycloak
              key: BADGERDOC_CLIENT_SECRET
        - name: ADMIN_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: users-keycloak
              key: ADMIN_CLIENT_SECRET
        command: ["/bin/sh"]
        args: ["-c", "uvicorn src.main:app --host 0.0.0.0 --port 8080 --root-path /api/v1/users"]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: "{{ .Values.schedulerName }}"
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      terminationGracePeriodSeconds: 30
