apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "svc.name" . }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "svc.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ template "svc.name" . }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}"
        app: "{{ template "svc.name" . }}"
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
      - image: {{ .Values.image.registry }}/jobs:{{ .Values.image.tag }}
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        name: jobs
        resources:
{{ toYaml .Values.resources | indent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: POSTGRESQL_JOBMANAGER_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: jobs
              key: DATABASE_URL
        - name: PIPELINES_URI
          value: "pipelines"
        - name: ASSETS_URI
          value: "assets"
        - name: ANNOTATION_MICROSERVICE_URI
          value: "annotation"
        - name: KEYCLOAK_HOST
          value: "{{ .Values.keycloak.externalUrl }}"
        command: ["/bin/sh"]
        args: ["-c", "alembic upgrade head && uvicorn jobs.main:app --host 0.0.0.0 --port 8123 --root-path /api/v1/jobs"]
      serviceAccountName: {{ default .Values.global.rbac.serviceAccountName .Values.rbac.serviceAccountName }}
      automountServiceAccountToken: {{ default .Values.global.rbac.automountToken .Values.rbac.automountToken }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: "{{ .Values.schedulerName }}"
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      terminationGracePeriodSeconds: 30
