apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: gotenberg
  labels:
    app: gotenberg
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: gotenberg
          image: gotenberg/gotenberg:7.4.3-cloudrun
          ports:
            - name: gotenberg
              containerPort: 3000
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          # dnsPolicy: ClusterFirst
          # restartPolicy: Always
          # schedulerName: default-scheduler
          # securityContext: {}
          # terminationGracePeriodSeconds: 30
