kind: Service
apiVersion: v1
metadata:
  name: gotenberg
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: gotenberg
      port: 3000
      targetPort: 3000
  selector:
    app: gotenberg
