global:
  db:
    host: postgres-postgresql-xxx
    port: 5432
  s3:
    endpoint: "http://minio"
  host: yourexample.com
  rbac:
    serviceAccountName: "serviceaccount"
    automountToken: false

annotation:
  affinity: {}
  db:
    host: null
    port: null
    name: "annotation"
  image:
    registry: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc
    tag: latest
  imagePullPolicy: Always
  nodeSelector: {}
  replicaCount: 1
  s3:
    endpoint: null
  secret:
    dbpassword: postgres
    dbuser: postgres
    enabled: true
    s3password: null
    s3user: null
  tolerations: []

assets:
  image:
    registry: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc
    tag: latest
  imagePullPolicy: Always
  podAnnotations:
    sidecar.istio.io/inject: "false"
  labels:
    app: assets
  replicaCount: 1
  resources:
    requests:
      memory: "200Mi"
      cpu: "200m"
    limits:
      memory: "1000Mi"
      cpu: "500m"
  s3:
    endpoint: null
  affinity: {}
  nodeSelector: {}
  tolerations: []
  secret:
    enabled: true
    dburl: "postgresql+psycopg2://postgres:postgres@postgres-postgresql:5432/file_management"
    s3user: null
    s3password: null
  securityContext: {}
  servicePort: 80
  serviceType: ClusterIP
  updateStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

jobs:
  image:
    registry: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc
    tag: latest
  podAnnotations:
    sidecar.istio.io/inject: "false"
  labels:
    app: jobs
  replicaCount: 1
  resources:
    requests:
      memory: "200Mi"
      cpu: "200m"
    limits:
      memory: "2000Mi"
      cpu: "500m"
  keycloak:
    externalUrl: "http://example.com"
  nameOverride: ""
  affinity: {}
  nodeSelector: {}
  tolerations: []
  secret:
    enabled: true
    dburl: "postgresql+psycopg2://postgres:postgres@postgres-postgresql:5432/job_manager"
  securityContext: {}

users:
  image:
    registry: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc
    tag: latest
  podAnnotations:
    sidecar.istio.io/inject: "false"
  labels:
    app: users
  replicaCount: 1
  resources:
    requests:
      memory: "100Mi"
      cpu: "200m"
    limits:
      memory: "1200Mi"
      cpu: "600m"
  s3:
    endpoint: null
  db:
    host: null
    port: null
    name: "users"
  keycloak:
    externalUrl: "http://example.com"
    internalUrl: "http://bagerdoc-keycloack"
  secret:
    enabled: true
    dbuser: "postgres"
    dbpassword: "postgres"
    s3user: null
    s3password: null

web:
  image:
    registry: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc
    tag: latest
  podAnnotations:
    sidecar.istio.io/inject: "false"
  labels:
    app: badgerdoc-ui
  replicaCount: 1
  resources: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  servicePort: 80
  serviceType: ClusterIP


