global:
  affinity: null
  labels: null
  nodeSelector: null
  tolerations: null
  podAnnotations:
    sidecar.istio.io/inject: "false"
  dbHost: postgres-postgresql
  dbPort: 5432
  s3Endpoint: "http://minio"
  host: yourexample.com
  imagePullPolicy: Always
  serviceAccountName: null
  automountToken: false
  resources:
    requests:
      memory: "000Mi"
      cpu: "000m"
    limits:
      memory: "0000Mi"
      cpu: "000m"
  schedulerName: null
  servicePort: 80
  serviceType: ClusterIP
  updateStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

annotation:
  dbName: "annotation"
  imageName: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc/annotation
  imageTag: 0.1.5-379754b
  secret:
    dbpassword: postgres
    dbuser: postgres
    enabled: true

assets:
  imageName: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc/assets
  imageTag: 0.1.7-379754b
  secret:
    enabled: true
    dbUrl: "postgresql+psycopg2://postgres:postgres@postgres-postgresql:5432/file_management"


jobs:
  imageName: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc/jobs
  imageTag: 0.1.9-379754b
  keycloak:
    externalUrl: "http://example.com"
  secret:
    enabled: true
    dbUrl: "postgresql+psycopg2://postgres:postgres@postgres-postgresql:5432/job_manager"


users:
  imageName: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc
  imageTag: 0.1.2-379754b
  dbName: "users"
  keycloak:
    externalUrl: "http://example.com"
    internalUrl: "http://bagerdoc-keycloak"
  secret:
    enabled: true
    dbuser: "postgres"
    dbpassword: "postgres"

badgerdoc-ui:
  imageName: 818863528939.dkr.ecr.eu-central-1.amazonaws.com/badgerdoc/badgerdoc_ui
  imageTag: 0.2.0-379754b


